native-image:
  build:
    additional-args:
      - "-J-Xmx3072m"
      - "-H:IncludeResourceBundles=net.sourceforge.argparse4j.internal.ArgumentParserImpl"
      - "-Ob" # Quick build mode
  agent:
    args:
      - ['--debug', 'false', '--path', 'src/test/resources/data/valid']
      - ['--debug', 'false', '--path', 'src/test/resources/data/invalid']
      - ['--debug', 'false', '--path', 'src/test/resources/data/invalid2']
      - ['--debug', 'true', '--path', 'src/test/resources/data/valid']
      - ['--debug', 'true', '--path', 'src/test/resources/data/invalid']
      - ['--debug', 'true', '--path', 'src/test/resources/data/invalid2']
      - ['--allow-duplicate-keys', 'false', '--path', 'src/test/resources/data/duplicate']
      - ['--allow-duplicate-keys', 'true', '--path', 'src/test/resources/data/duplicate']
      - [ '--ignore-unknown-tags', 'false', '--path', 'src/test/resources/data/tags' ]
      - [ '--ignore-unknown-tags', 'true', '--path', 'src/test/resources/data/tags' ]
      - []
      - ['--help']